### ISSUE TITLE
Prefill People picker

### ISSUE THREAD

**Issue by mvahsen** [gunjandatta/sprest-react#7]
Hi Gunjan,

I'm trying to prefill the People picker on page load.  From gd-sprest-react -> people.picker.D.ts

```
<Components.SPPeoplePicker
  ref={picker => { this._spPicker = picker; }}
/>

public componentDidMount() {
    this._spPicker.clientPeoplePickerSearchUser({
    MaximumEntitySuggestions: 10,
    PrincipalSource: 15,
    PrincipalType: 15,
    QueryString: “Marco”
  }).executeAndWait();
}
```
the main problem is setting a default value to the people picker.
Something like "this._spPicker.clientPeoplePickerSearchUser"  doesn't work.
Do you have an idea how to prefill the people picker component with a defined user?

Best regards

Marco

**Comment by gunjandatta** [comment]
You can pass in an array of type FieldUserValue (SP.ComplexTypes.FieldUserValue) or number. The number is in reference to the associated item id for the user or group. I'm not sure what or how you are trying to render the picker, so if you can provide a little more info I can better assist. From the info I have, you could query for the data, and pass in the results to the people picker as a value.

**Comment by gunjandatta** [comment]
I'll assume you are using TypeScript, you can always reference the "gd-sprest" library and import the ContextInfo component to get the current user id, and pass that into the SPPeoplePicker:

```
import { ContextInfo } from "gd-sprest";

public render() {
  // Set the field value
  fieldValue = [ContextInfo.userId];

  // Render the picker
  return (
    <Components.SPPeoplePicker ref={ picker => { this._spPicker = picker; } fieldValue={fieldValue} />
  );
}
```

This should work. If you wanted to pass in the search values, then reference the code below.

```
import { PeoplePicker } from "gd-sprest";

PeoplePicker().clientPeoplePickerSearchUser({
    MaximumEntitySuggestions: 10,
    PrincipalSource: 15,
    PrincipalType: 15,
    QueryString: “Marco”
}).execute(search => {
  // The search results can be passed into the people picker
  // Save the fieldValue to your state and apply it to the people picker
  let fieldValue = search.ClientPeoplePickerSearchUser;
});
```

Let me know if this doesn't work, or if you have any other issues. I hope this helps solve the issue.

**Comment by mvahsen** [comment]
Hi Gunjan,

the most promising solution and simplest:

```
import { ContextInfo } from "gd-sprest";

    public render() {
        let fieldValue = [ContextInfo.userId];

return (
    <Components.SPPeoplePicker ref={ picker => { this._spPicker = picker; } fieldValue={fieldValue} />
  );
}
```
has the error
[tsl] ERROR
TS2322: Type 'number[]' is not assignable to type 'FieldUserValue[]'.

Tried to make a FieldUserValue and set the user ID with [ContextInfo.userId] and made an array out of it but with no luck, the picker remains empty.

```
public render() {
  let fieldValues: Types.SP.ComplexTypes.FieldUserValue[];
      for (var i = 0; i < [ContextInfo.userId].length-1; i++) {
            let fieldValue: Types.SP.ComplexTypes.FieldUserValue;
            fieldValue.ID = [ContextInfo.userId][i];
            fieldValues.push(fieldValue);
        }

```

2nd possibility:

```
public render() {
 let picker = new PeoplePicker;
 picker.clientPeoplePickerSearchUser({
            MaximumEntitySuggestions: 10,
            PrincipalSource: 15,
            PrincipalType: 15,
            QueryString: "Marco"
        }).execute(search => {
             {
               let fieldValue = search.ClientPeoplePickerSearchUser;
             });
```
doesn't show an error but the picker remains empty

**Comment by gunjandatta** [comment]
I'll update the definition file and any other code updates to get this to work today, and let you know when it's done.

**Comment by gunjandatta** [comment]
v2.9.4 has the code updates. I also updated all of the core libraries, since this wasn't done for a while The office fabric ui components were well out of date. Please let me know if you have any issues.

**Comment by gunjandatta** [comment]
v2.9.5 has an intellisense update for this request. I tested the people picker w/ the following code shown below, and it defaulted to the current user.

```tsx
<Components.SPPeoplePicker
     fieldValue={[ContextInfo.userId]}
/>
```

Please close this issue out, or let me know if you have any other issues. Thanks for posting this request.

**Comment by mvahsen** [comment]
Late reply but needed a day with less work to update all the references.
Thanks for all the help

**Comment by gunjandatta** [comment]
Sorry about that. This library hasn’t been updated in a while, so I went ahead and included it. I hope the references/updates were straight forward.
